server:
    port: 9000

eureka:
    server:
        renewal-percent-threshold: 0.49
    client:
        service-url:
            defaultZone: http://localhost:${server.port}/eureka
        register-with-eureka: false
        fetch-registry: false
logging:
    pattern:
        dateformat: yyyy-MM-dd HH:mm:ss

