server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: app
            uri: lb://uniapp
            predicates:
              - path=/api/**
            filters:
              - StripPrefix=1
