server:
  port: 10001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
spring:
  application:
    name: user-service
mybatis-flex:
  datasource:
    ds1:
      url: jdbc:mysql://localhost:3306/ptt
      username: root
      password: LWT5201314wan..
file:
  base: D:\Cache\SCExam\
